In [216]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set() # Apply the default seaborn theme, scaling, and color palette

import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [217]:
df1 = pd.read_csv("RTOdata.csv")
df2 = pd.read_csv("RTO_data_new.csv")
df = pd.concat([df1, df2], ignore_index=True)
df.head()

,OrderId,UserId,OrderValue,PaymentType,District,OrderSource,OrderType,DeliveryCharge,OrderPlacedDay,OrderConfirmDayOverPhone,IsCartOrder,OrderFromPromotionalEvent,isRTO,courierService
0,2562691,663791,168,MPD,Dhaka,android,normal,25.0,6/26/2019 9:20,6/26/2019 3:30,No,Yes,No,NaN
1,2561859,961083,240,MPD,Dhaka,mobile-site,normal,35.0,6/25/2019 19:05,6/25/2019 13:40,No,Yes,No,NaN
2,2561434,848517,120,MPD,Dhaka,desktop,normal,35.0,6/25/2019 15:28,6/25/2019 9:27,No,Yes,Yes,NaN
3,2561202,276304,185,MPD,Dhaka,android,normal,25.0,6/25/2019 13:27,6/25/2019 7:27,Yes,No,No,NaN
4,2561033,955384,201,MPD,Dhaka,android,normal,25.0,6/25/2019 12:13,6/25/2019 6:56,No,Yes,No,NaN

In [218]:
df.shape

(20000, 14)

In [219]:
df.dtypes

OrderId                        int64
UserId                         int64
OrderValue                     int64
PaymentType                   object
District                      object
OrderSource                   object
OrderType                     object
DeliveryCharge               float64
OrderPlacedDay                object
OrderConfirmDayOverPhone      object
IsCartOrder                   object
OrderFromPromotionalEvent     object
isRTO                         object
 courierService               object
dtype: object

In [220]:
del df['OrderId']

In [221]:
df['OrderPlacedDay'] = pd.to_datetime(df['OrderPlacedDay'] )
df['OrderConfirmDayOverPhone'] = pd.to_datetime(df['OrderConfirmDayOverPhone'] )
df.head()

,UserId,OrderValue,PaymentType,District,OrderSource,OrderType,DeliveryCharge,OrderPlacedDay,OrderConfirmDayOverPhone,IsCartOrder,OrderFromPromotionalEvent,isRTO,courierService
0,663791,168,MPD,Dhaka,android,normal,25.0,2019-06-26 09:20:00,2019-06-26 03:30:00,No,Yes,No,NaN
1,961083,240,MPD,Dhaka,mobile-site,normal,35.0,2019-06-25 19:05:00,2019-06-25 13:40:00,No,Yes,No,NaN
2,848517,120,MPD,Dhaka,desktop,normal,35.0,2019-06-25 15:28:00,2019-06-25 09:27:00,No,Yes,Yes,NaN
3,276304,185,MPD,Dhaka,android,normal,25.0,2019-06-25 13:27:00,2019-06-25 07:27:00,Yes,No,No,NaN
4,955384,201,MPD,Dhaka,android,normal,25.0,2019-06-25 12:13:00,2019-06-25 06:56:00,No,Yes,No,NaN

In [222]:
df['DelayConfirmation'] =df['OrderConfirmDayOverPhone'].dt.date - df['OrderPlacedDay'].dt.date
df.head()

,UserId,OrderValue,PaymentType,District,OrderSource,OrderType,DeliveryCharge,OrderPlacedDay,OrderConfirmDayOverPhone,IsCartOrder,OrderFromPromotionalEvent,isRTO,courierService,DelayConfirmation
0,663791,168,MPD,Dhaka,android,normal,25.0,2019-06-26 09:20:00,2019-06-26 03:30:00,No,Yes,No,NaN,0 days
1,961083,240,MPD,Dhaka,mobile-site,normal,35.0,2019-06-25 19:05:00,2019-06-25 13:40:00,No,Yes,No,NaN,0 days
2,848517,120,MPD,Dhaka,desktop,normal,35.0,2019-06-25 15:28:00,2019-06-25 09:27:00,No,Yes,Yes,NaN,0 days
3,276304,185,MPD,Dhaka,android,normal,25.0,2019-06-25 13:27:00,2019-06-25 07:27:00,Yes,No,No,NaN,0 days
4,955384,201,MPD,Dhaka,android,normal,25.0,2019-06-25 12:13:00,2019-06-25 06:56:00,No,Yes,No,NaN,0 days

In [223]:
for ind in df.index:
    df['DelayConfirmation'][ind] = str(df['DelayConfirmation'][ind]).replace('00:00:00','').replace('days','')
    df['DelayConfirmation'][ind] = int(df['DelayConfirmation'][ind])
df.head()

,UserId,OrderValue,PaymentType,District,OrderSource,OrderType,DeliveryCharge,OrderPlacedDay,OrderConfirmDayOverPhone,IsCartOrder,OrderFromPromotionalEvent,isRTO,courierService,DelayConfirmation
0,663791,168,MPD,Dhaka,android,normal,25.0,2019-06-26 09:20:00,2019-06-26 03:30:00,No,Yes,No,NaN,0
1,961083,240,MPD,Dhaka,mobile-site,normal,35.0,2019-06-25 19:05:00,2019-06-25 13:40:00,No,Yes,No,NaN,0
2,848517,120,MPD,Dhaka,desktop,normal,35.0,2019-06-25 15:28:00,2019-06-25 09:27:00,No,Yes,Yes,NaN,0
3,276304,185,MPD,Dhaka,android,normal,25.0,2019-06-25 13:27:00,2019-06-25 07:27:00,Yes,No,No,NaN,0
4,955384,201,MPD,Dhaka,android,normal,25.0,2019-06-25 12:13:00,2019-06-25 06:56:00,No,Yes,No,NaN,0

In [224]:
df['OrderDate'] = df.OrderPlacedDay.dt.dayofweek
df['ConfirmDate'] = df.OrderConfirmDayOverPhone.dt.dayofweek
df.head(2)

,UserId,OrderValue,PaymentType,District,OrderSource,OrderType,DeliveryCharge,OrderPlacedDay,OrderConfirmDayOverPhone,IsCartOrder,OrderFromPromotionalEvent,isRTO,courierService,DelayConfirmation,OrderDate,ConfirmDate
0,663791,168,MPD,Dhaka,android,normal,25.0,2019-06-26 09:20:00,2019-06-26 03:30:00,No,Yes,No,NaN,0,2,2
1,961083,240,MPD,Dhaka,mobile-site,normal,35.0,2019-06-25 19:05:00,2019-06-25 13:40:00,No,Yes,No,NaN,0,1,1

In [225]:
del df['OrderConfirmDayOverPhone']
del df['OrderPlacedDay']

In [226]:
df.tail(2)

,UserId,OrderValue,PaymentType,District,OrderSource,OrderType,DeliveryCharge,IsCartOrder,OrderFromPromotionalEvent,isRTO,courierService,DelayConfirmation,OrderDate,ConfirmDate
19998,967577,409,MPD,Dhaka,android,normal,25.0,No,No,No,E-Desh ...,0,2,2
19999,970326,402,MPD,Moulvibazar,android,normal,60.0,No,Yes,Yes,Paperfly ...,0,2,2

In [227]:
df.isna().sum()

UserId                           0
OrderValue                       0
PaymentType                      0
District                         0
OrderSource                      0
OrderType                      681
DeliveryCharge                   1
IsCartOrder                      0
OrderFromPromotionalEvent        0
isRTO                            0
 courierService              10000
DelayConfirmation                0
OrderDate                        0
ConfirmDate                      0
dtype: int64

In [228]:
df.columns = ['UserId','OrderValue','PaymentType','District','OrderSource','OrderType','DeliveryCharge','IsCartOrder','OrderFromPromotionalEvent','isRTO'
             , 'Courier','DelayConfirmation','OrderDate','ConfirmDate'
             ]

In [229]:
for ind in df.index:
    if pd.isnull(df['OrderType'][ind]):
        if df['DeliveryCharge'][ind] >=75:
            df['OrderType'][ind] = 'express'
        else:
            df['OrderType'][ind]='normal'

In [230]:
df.isna().sum()

UserId                           0
OrderValue                       0
PaymentType                      0
District                         0
OrderSource                      0
OrderType                        0
DeliveryCharge                   1
IsCartOrder                      0
OrderFromPromotionalEvent        0
isRTO                            0
Courier                      10000
DelayConfirmation                0
OrderDate                        0
ConfirmDate                      0
dtype: int64

In [231]:
# data = df.copy()
# del df['courierService']

In [232]:
df['Courier'].fillna(df['Courier'].value_counts().idxmax(),inplace=True)
df['DeliveryCharge'].fillna(55,inplace=True)

In [233]:
cols = ['Courier','OrderType','OrderSource','PaymentType']
for col in cols:
    print(df[col].unique())

['E-Desh                                                                                              '
 'E-Courier LTD                                                                                       '
 'Paperfly                                                                                            '
 'Office Delivery                                                                                     '
 'Bangladesh Postal Service                                                                           '
 'Delivery Tiger                                                                                      ']
['normal' 'express']
['android' 'mobile-site' 'desktop' '-1' 'Others' 'byphone' 'ajkerdeal'
 'www.google.com' 'A2I']
['MPD                 ' 'ADC                 ' 'MPC                 '
 'OPS                 ' 'MPS                 ' 'EMI                 '
 'E-COD               ']

In [234]:
df.isna().sum()

UserId                       0
OrderValue                   0
PaymentType                  0
District                     0
OrderSource                  0
OrderType                    0
DeliveryCharge               0
IsCartOrder                  0
OrderFromPromotionalEvent    0
isRTO                        0
Courier                      0
DelayConfirmation            0
OrderDate                    0
ConfirmDate                  0
dtype: int64

In [235]:
cat_cols = ['PaymentType','District','OrderSource','OrderType','IsCartOrder','OrderFromPromotionalEvent','isRTO','Courier']
for col in cat_cols:
    df[col] = df[col].astype('category')
    print(col,'---->', dict(enumerate(df[col].cat.categories)))
    df[col] = df[col].cat.codes

PaymentType ----> {0: 'ADC                 ', 1: 'E-COD               ', 2: 'EMI                 ', 3: 'MPC                 ', 4: 'MPD                 ', 5: 'MPS                 ', 6: 'OPS                 '}
District ----> {0: 'Bagerhat', 1: 'Bandarban', 2: 'Barguna', 3: 'Barisal', 4: 'Bhola', 5: 'Bogra', 6: 'Brahmanbaria', 7: 'Chandpur', 8: 'Chapai-Nawabganj', 9: 'Chittagong (Outside City)', 10: 'Chittagong City', 11: 'Chuadanga', 12: 'Comilla', 13: "Cox's-Bazar", 14: 'Dhaka', 15: 'Dhaka (Outside City)', 16: 'Dinajpur', 17: 'Faridpur', 18: 'Feni', 19: 'Gaibandha', 20: 'Gazipur', 21: 'Gopalganj', 22: 'Habiganj', 23: 'Jamalpur', 24: 'Jessore', 25: 'Jhalokati', 26: 'Jhenaidah', 27: 'Joypurhat', 28: 'Khagrachhari', 29: 'Kishoreganj', 30: 'Kurigram', 31: 'Kushtia', 32: 'Lakshmipur', 33: 'Lalmonirhat', 34: 'Madaripur', 35: 'Magura', 36: 'Manikganj', 37: 'Meherpur', 38: 'Moulvibazar', 39: 'Munshiganj', 40: 'Mymensingh', 41: 'Naogaon', 42: 'Narail', 43: 'Narayanganj', 44: 'Narsingdi', 45: 'Natore', 46: 'Netrokona', 47: 'Nilphamari', 48: 'Noakhali', 49: 'Pabna', 50: 'Panchagarh', 51: 'Patuakhali', 52: 'Pirojpur', 53: 'Rajbari', 54: 'Rajshahi (Outside City)', 55: 'Rajshahi City', 56: 'Rangamati', 57: 'Rangpur', 58: 'Satkhira', 59: 'Shariatpur', 60: 'Sherpur', 61: 'Sirajganj', 62: 'Sunamganj', 63: 'Sylhet (Outside City)', 64: 'Sylhet City', 65: 'Tangail', 66: 'Thakurgaon', 67: 'khulna (Outside City)', 68: 'khulna City'}
OrderSource ----> {0: '-1', 1: 'A2I', 2: 'Others', 3: 'ajkerdeal', 4: 'android', 5: 'byphone', 6: 'desktop', 7: 'mobile-site', 8: 'www.google.com'}
OrderType ----> {0: 'express', 1: 'normal'}
IsCartOrder ----> {0: 'No', 1: 'Yes'}
OrderFromPromotionalEvent ----> {0: 'No', 1: 'Yes'}
isRTO ----> {0: 'No', 1: 'Yes'}
Courier ----> {0: 'Bangladesh Postal Service                                                                           ', 1: 'Delivery Tiger                                                                                      ', 2: 'E-Courier LTD                                                                                       ', 3: 'E-Desh                                                                                              ', 4: 'Office Delivery                                                                                     ', 5: 'Paperfly                                                                                            '}

In [236]:
df.head(2)

,UserId,OrderValue,PaymentType,District,OrderSource,OrderType,DeliveryCharge,IsCartOrder,OrderFromPromotionalEvent,isRTO,Courier,DelayConfirmation,OrderDate,ConfirmDate
0,663791,168,4,14,4,1,25.0,0,1,0,3,0,2,2
1,961083,240,4,14,7,1,35.0,0,1,0,3,0,1,1

In [237]:
df.corr()

,UserId,OrderValue,PaymentType,District,OrderSource,OrderType,DeliveryCharge,IsCartOrder,OrderFromPromotionalEvent,isRTO,Courier,OrderDate,ConfirmDate
UserId,1.000000,-0.030584,0.023869,0.057585,-0.009490,-0.003787,0.141370,-0.113414,0.008780,0.023850,0.034496,-0.006612,-0.011251
OrderValue,-0.030584,1.000000,0.027050,-0.003550,0.091483,-0.046969,0.104155,-0.112958,-0.285980,0.028069,-0.011308,0.002876,0.001767
PaymentType,0.023869,0.027050,1.000000,-0.001258,0.051536,-0.008826,-0.109563,0.093904,0.167330,-0.038940,0.024153,0.016429,0.018555
District,0.057585,-0.003550,-0.001258,1.000000,-0.067346,-0.092387,0.180890,-0.005023,-0.005471,-0.074084,0.023357,0.019638,0.021226
OrderSource,-0.009490,0.091483,0.051536,-0.067346,1.000000,-0.158506,0.083095,-0.011109,-0.078009,0.021686,-0.013061,0.001520,-0.003170
OrderType,-0.003787,-0.046969,-0.008826,-0.092387,-0.158506,1.000000,-0.239772,0.038725,0.051293,0.033456,-0.016942,-0.005922,-0.006360
DeliveryCharge,0.141370,0.104155,-0.109563,0.180890,0.083095,-0.239772,1.000000,-0.470498,-0.049172,0.007567,0.056763,0.029194,0.028475
IsCartOrder,-0.113414,-0.112958,0.093904,-0.005023,-0.011109,0.038725,-0.470498,1.000000,0.135502,-0.047434,0.001663,-0.022579,-0.023056
OrderFromPromotionalEvent,0.008780,-0.285980,0.167330,-0.005471,-0.078009,0.051293,-0.049172,0.135502,1.000000,0.001516,0.018577,-0.001848,0.000635
isRTO,0.023850,0.028069,-0.038940,-0.074084,0.021686,0.033456,0.007567,-0.047434,0.001516,1.000000,-0.007621,-0.001938,-0.003886
Courier,0.034496,-0.011308,0.024153,0.023357,-0.013061,-0.016942,0.056763,0.001663,0.018577,-0.007621,1.000000,0.016659,0.014065
OrderDate,-0.006612,0.002876,0.016429,0.019638,0.001520,-0.005922,0.029194,-0.022579,-0.001848,-0.001938,0.016659,1.000000,0.958504
ConfirmDate,-0.011251,0.001767,0.018555,0.021226,-0.003170,-0.006360,0.028475,-0.023056,0.000635,-0.003886,0.014065,0.958504,1.000000

In [238]:
df['Courier'].unique()

array([3, 2, 5, 4, 0, 1], dtype=int8)

In [239]:
del df['Courier']
df.DelayConfirmation = df.DelayConfirmation.astype('int64')

In [256]:
from sklearn.model_selection import train_test_split

X = df.loc[:, df.columns!='isRTO']
y = df.loc[:, df.columns=='isRTO']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

print("""X_train:{}
y_train:{}
X_test: {}
y_test: {}""".format(X_train.shape, y_train.shape, X_test.shape, y_test.shape))

X_train:(16000, 12)
y_train:(16000, 1)
X_test: (4000, 12)
y_test: (4000, 1)

In [257]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int8)

In [258]:
from sklearn.metrics import accuracy_score

model1 = LogisticRegression()
model1.fit(X_train, y_train)
y1_pred = model1.predict(X_test)
acc1 = accuracy_score(y_test, y1_pred)

model2 = LogisticRegression(C=0.05179474679231213, penalty='l2')
model2.fit(X_train, y_train)
y2_pred = model2.predict(X_test)
acc2 = accuracy_score(y_test, y2_pred)

print("""Model 1: {}
Model 2: {}""".format(acc1, acc2))

Model 1: 0.87025
Model 2: 0.87025

In [259]:
df.dtypes

UserId                         int64
OrderValue                     int64
PaymentType                     int8
District                        int8
OrderSource                     int8
OrderType                       int8
DeliveryCharge               float64
IsCartOrder                     int8
OrderFromPromotionalEvent       int8
isRTO                           int8
DelayConfirmation              int64
OrderDate                      int64
ConfirmDate                    int64
dtype: object

In [260]:
import xgboost as xgb
xgb_model = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=10,
              min_child_weight=1, missing=None, n_estimators=200, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)
xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)

print("XGB Accuracy:", accuracy_score(y_test, xgb_pred))

XGB Accuracy: 0.8795